### ISSUE TITLE
Agency table updates

### ISSUE THREAD

**Issue by ld-greeninfo** [john-greeninfo/cpad#17]
There are some blanks values in the pre-release shapefiles that look like they should have been populated by the agency table (such as agncy_typ).

When a new agency is added to the master_agency table, do the fields "agncy_typ", "gap_ag_cod", "gap_ag_nam", "gap_ag_typ", and "agncy_uid" get auto-populated? Do we need to manually enter these values, and is there a definition list somewhere that lists gap codes?

**Comment by john-greeninfo** [comment]
Fields in master_agency do not get auto-populated. If they're desired in output the need to be entered along with the required fields agncy_id, agncy_name, agncy_lev, and layer.
